### ISSUE TITLE
Is there any official API doc for AE Scripts?

### ISSUE THREAD

**Issue by MickeyMiao7** [aenhancers/Types-for-Adobe#108]
Hi, I am new to adobe AE script developing. The reason i raise this issue is that it's hard for me to find any official API doc for AE scripting, and thats why this repo is so useful for me.
I found some knowledge in https://helpx.adobe.com/after-effects/using/expression-language.html but most of them are deprecated. 
I am sorry that probably it is not a good place to raise this question, but i am really curious how you guys find the AE API. Is there any useful suggestions for developing / debugging AE scripts?

**Comment by johhnry** [comment]
Hi @MickeyMiao7,

I suppose you are talking about Adobe's ExtendScript instead of After Effects expressions, if so you can see the documentation here:

https://ae-scripting.docsforadobe.dev/index.html

**Comment by aeksco** [comment]
@MickeyMiao7 I'm very new to the Adobe scripting and I too have found documentation to be sparse.

I had a lot of success using ChatGPT to help write and explain Illustrator scripts - it's been an invaluable resource to get some Illustrator automation scripts off the ground and I highly recommend experimenting with it!

**Comment by MickeyMiao7** [comment]
> @MickeyMiao7 I'm very new to the Adobe scripting and I too have found documentation to be sparse.
> 
> I had a lot of success using ChatGPT to help write and explain Illustrator scripts - it's been an invaluable resource to get some Illustrator automation scripts off the ground and I highly recommend experimenting with it!

thx so much!
