### ISSUE TITLE
Group.alignChildren can take a string or [string, string] argument

### ISSUE THREAD

**Issue by sebastianiorga** [aenhancers/Types-for-Adobe#32]
Tested with `Group.alignChildren` for InDesign CC 2018. I assume this issue affects the `_Control` `alignment` definition as well as other `alignChildren` definitions.

http://jongware.mit.edu/idcs6js/pc_Group%20(SUI).html according to this(as well as testing in InDesign CC 2018) `alignment` can take an argument of the form [horizontal: string, vertical: string]. By extension(and testing) `alignChildren` can as well.

The doc comment in ScriptUI.d.ts for `alignment` mentions that but `alignChildren` does not.

**Comment by pravdomil** [comment]
@sebastianiorga thanks for notice, PR are welcome :)

**Comment by zlovatt** [comment]
Fixed in #114
