### ISSUE TITLE
Adobe After Effects: Undefined Types

### ISSUE THREAD

**Issue by mustapha-abdelaziz** [aenhancers/Types-for-Adobe#55]
The Layer type is undefined under adobe after effects

**Comment by pravdomil** [comment]
open pr

**Comment by zlovatt** [comment]
Closing as this isn't actionable. `Layer` is an internal base class; it _is_ defined when working with the API, however checking `instanceof Layer` will always return false as [actual layers have more specific instance types](https://ae-scripting.docsforadobe.dev/introduction/classhierarchy.html).
