### ISSUE TITLE
How can I import other scripts into mine?

### ISSUE THREAD

**Issue by SamuelCharpentier** [aenhancers/Types-for-Adobe#72]
I'm working on an Illustrator script

I usually use `#import 'json2.js'` at the begining of my files, but with typescript, there's a compile error. If I try to just remove the `#import` at the top, then I get a compile error stating "Cannot find name 'JSON'"

How can I import and get rid or these errors?

**Comment by zlovatt** [comment]
This issue doesn't really have anything to do with this repo, but:

You can use `//@include 'json2.js'` as an alternative syntax. See [the Extendscript docs](https://extendscript.docsforadobe.dev/extendscript-tools-features/preprocessor-directives.html#include-file).

**Comment by wadimw** [comment]
You can also check out my sample project which supports CommonJS modules https://github.com/wadimw/extendscript-ts-sample-project
