### ISSUE TITLE
Project setup including all supported standard Javascript classes 

### ISSUE THREAD

**Issue by patrickheinzelmann** [aenhancers/Types-for-Adobe#82]
Hi,

I have setup my project according to the Readme file and video instructions for an Indesign script.

As I understand, Adobe Creative Cloud apps support a subset of the standard Javascript classes e.g. JSON. Inside my script I have to read a JSON file.

How do I have to update the generated Typescript project (package.json, tsconfig.json), so that I can use the support classes like JSON.

Thanks
Patrick

**Comment by wadimw** [comment]
Hi,

you can check out my sample project here https://github.com/wadimw/extendscript-ts-sample-project
