### ISSUE TITLE
Photoshop stringIDToTypeID/charIDToTypeID/executeAction etc?

### ISSUE THREAD

**Issue by Dariusz1989** [aenhancers/Types-for-Adobe#84]
Hey

Any idea where I can get declaration/info on 
stringIDToTypeID
charIDToTypeID
executeAction
etc?

**Comment by bioRex21** [comment]
I found this official PDF where those are mentioned: https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-javascript-ref-2020.pdf

And there's this other project (uses other language) that might serve as reference:
https://github.com/SlavaRa/haxelib-extendscript/blob/master/extendscript/photoshop/Application.hx#L249

Hope this helps.

**Comment by zlovatt** [comment]
Closing this ticket; those methods are present in this repo, and usage info is found in the scripting guides; seems there's nothing actionable here.
